version: "3.8"

services:
  db:
    image: postgres:10-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  
